Update Forkdiff
sunnyside-io/op-erigon pull request #214
Opened 2024-08-11 07:40 UTC by mininny

2024-08-12 22:09 UTC, ImTei commented on cl/persistence/state/minimal_state.go
Why did you delete these files?

2024-08-13 10:12 UTC, mininny commented on cl/persistence/state/minimal_state.go
These files were deleted from upstream erigon, and are not modified on our end, which means they aren't necessary.

2024-08-13 21:01 UTC, pcw109550 requested changes
List of suggestions
- Can you remove `erigon-lib` hyperlink because it is not used anymore?
- Also ignore diffs for core/allocs/optimism_devnet.json because this diff adds +15277 line diffs but only needed for genesis allocs.

2024-08-17 03:27 UTC, mininny commented
> List of suggestions
> 
> * Can you remove `erigon-lib` hyperlink because it is not used anymore?
> * Also ignore diffs for core/allocs/optimism_devnet.json because this diff adds +15277 line diffs but only needed for genesis allocs.

@pcw109550 Thanks for the suggestions! I removed `erigon-lib` and ignored the diffs for the .json file. 
What about `_test.go` files? What do you think about moving them all to the "Testing" section and have them ignored since they increase the diff so much? https://op-geth.optimism.io/ geth also has most of the tests in the Testing section as well.

2024-08-22 07:37 UTC, pcw109550 commented
@mininny ignoring test files will make forkdiff more consistent with op-geth forkdiff so i totally agree with that idea.

2024-08-22 15:08 UTC, mininny commented
> @mininny ignoring test files will make forkdiff more consistent with op-geth forkdiff so i totally agree with that idea.

It's updated! :)

2024-08-23 06:31 UTC, pcw109550 approved these changes

2024-08-24 00:29 UTC, merged